name: build and run simple test

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install gcc
        run: apt update && apt install gcc
      - name: create build env
        run: cmake -Bbuild
      - name: build
        run: cmake --build build
      - name: run tests
        run: ctest --test-dir build
        env:
          DB_PATH: ${{runner.workspace}}/dbfile
             
